# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-added-large-files
      - id: end-of-file-fixer
  - repo: https://github.com/hhatto/autopep8
    rev: "v2.3.2"
    hooks:
      - id: autopep8
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        exclude: .*jenkins-slave$
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        args:
          - --ignore=DL3015 # Ignore not using --no-install-recommends with apt
          - --ignore=DL3008 # Ignore not pinning all software package versions (apt-get)
          - --ignore=DL3018 # Ignore not pinning all software package versions (apk)
          - --ignore=SC1091 # Ignore missing shellcheck mock files
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.30"
    hooks:
      - id: terraform-validate
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.93.4
    hooks:
      - id: trufflehog
        entry: bash -c 'git diff --cached --name-only | xargs -I {} trufflehog filesystem {} --fail --only-verified --log-level=-1'
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
